### ISSUE TITLE
Custom marker placement issue (only for map pointer images)

### ISSUE THREAD

**Issue by ghost** [mappls-api/mapmyindia-maps-vectorSDK-iOS#2]
hello, when i try use CustomPointAnnotation with [map pointer](https://www.iconfinder.com/icons/254221/direction_location_map_pointer_icon) the icon getting placed on the center point of the coordinates. Since its marker I just want to place the bottom edges on the coordinates. I have tried [this sample code](https://docs.mapbox.com/ios/maps/examples/marker-image/) in **_imagefor Annotation_** and direct method as well, still marker is placed in center only.
Could you plz check and provide the solutions for this. if possible add the updated fix in sample mapDemo project custom marker section also..  thanks in advnc

**Comment by ayushdayal007** [comment]
You should use MGLAnnotationView instead of MGLAnnotationImage because MGLAnnotationView a descendant of UIView so you can add to it anything you want as with ordinary UIView And there is a centreOffset property available in MGLAnnotationView which can be used as follows:

func mapView(_ mapView: MGLMapView, viewFor annotation: MGLAnnotation) -> MGLAnnotationView? {
        var annotationView = MGLAnnotationView(annotation: annotation, reuseIdentifier: identifier)
        let imageView = UIImageView(image: image)
        annotationView!.frame = CGRect(x: 0, y: 0, width: image.size.width, height: image.size.height)
        annotationView?.addSubview(imageView)
        annotationView?.centerOffset = CGVector(dx: 0, dy: -image.size.height / 2.0)
        return annotationView
}
